spring.application.name=AirBnB-App

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/v1

frontend.url=http://localhost:8080

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

jwt.secretKey=${JWT_SECRET_KEY}

stripe.secret.key=${STRIPE_SECRET_KEY}

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

